name: Deploy - Cloudflax

on:
  push:
    branches:
      - master

jobs:
  checkout:
    name: Build & Deploy
    runs-on: ubuntu-24.04
    environment: Digital Ocean

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Deploy to Server
        uses: ngocquyhoang/deploy@laravel
        with:
          user: ${{ secrets.DO_SSH_USER }}
          host: ${{ secrets.DO_SSH_HOST }}
          port: 22
          path: /var/www/html/laravel
          owner: root
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}