name: Deploy - Cloudflax

on:
  push:
    branches:
      - master

jobs:
  checkout:
    name: Build & Deploy
    runs-on: ubuntu-24.04
    environment: Digital Ocean

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Upload files to DigitalOcean Droplet
        run: |
          rsync -avz --delete . ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }}:/var/www/html/laravel/